// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtjilnsyknblsuwqusur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0amlsbnN5a25ibHN1d3F1c3VyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMTY0MDEsImV4cCI6MjA2MDg5MjQwMX0.ULAWH2iiTt0U85LhwX63bwlQKno_3bSeJijm0IY7P4U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);